### PR TITLE
Changes to make the cookbook working with a recent Foreman release (1.14.1).

### PR DESCRIPTION
**Pull request by frzb**

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi and thanks for the pull request, I will have a look on tomorrow ;)
Regards

**Comment by frzb** [comment]
Still lots of trouble from `rspec` at  the Travis CI build. :disappointed:

**Comment by PierreRambaud** [comment]
LGTM, is this pull request is done?

**Comment by frzb** [comment]
Yes! Done.   :smile:

**Comment by PierreRambaud** [comment]
Thanks a lot :D

**Pull request merged**
