### PR TITLE
Chef configuration and bug fixes

### PR DESCRIPTION
**Pull request by PierreRambaud**
- Include #4 configuration of smart_proxy_chef
- Add .kitchen.local.yml into .gitignore
- Use chef zero as provisioner for kitchen
- Fix mysql database configuration
- Move plugins installation into specific recipe
- Fix database host value in database.yml

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Gentle ping!

**Comment by guilhem** [comment]
seems to be ok for me :)
:+1:

**Comment by PierreRambaud** [comment]
Gentle ping! If there is someone else to approved!

**Comment by guilhem** [comment]
@PierreRambaud I think you can merge it gently ;)

**Comment by PierreRambaud** [comment]
Thanks ;)

**Pull request merged**
