### PR TITLE
Updates for testing

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by shortdudey123** [comment]
@PierreRambaud let me know if you have any feedback for changes on your end

**Comment by PierreRambaud** [comment]
Hi and thanks for this pull request. I was on vacation and will have a look on tomorrow :) Thanks again

**Comment by shortdudey123** [comment]
No problem! hope you enjoyed your vacation :)

**Comment by PierreRambaud** [comment]
Ahah not really, i'm in relocation, moving to another city :D 
Thanks for your PR :)

**Comment by PierreRambaud** [comment]
Ahah not really, i'm in relocation, moving to another city :D 
Thanks for your PR :)

**Comment by shortdudey123** [comment]
ah fun and you are welcome!
More to come :)

**Pull request merged**
