### PR TITLE
Update to make it works for Chef 12

### PR DESCRIPTION
**Pull request by PierreRambaud**
Trying to convert puppet-foreman and puppet-foreman-proxy installation to a simple chef cookbook.

### CODE REVIEW

**Comment by guilhem** [comment]
Really nice work. I'm waiting for the merging request ;)

**Comment by PierreRambaud** [comment]
I'm curently in parental holliday and will ne back in few weeks to finish
this PR.
Thanks

**Comment by guilhem** [comment]
@PierreRambaud Congrats! :)

**Comment by PierreRambaud** [comment]
Hi,
It's almost the end, theforeman and foreman-proxy can be installed separately, but I need work on dhcp, bind, puppet, bmc and tftp configuration.
More I need improve rspec tests, create kitchen test, and improve readme file.
Chef provisioning is used to create and example vm (better than kitchen to test and play with network interfaces).

Regards

**Comment by PierreRambaud** [comment]
There are some other things to add, but a I think you can begin checking, and also activate travis ci.

**Comment by PierreRambaud** [comment]
I think it's ok, for a first release :)

**Comment by PierreRambaud** [comment]
Ping!

**Comment by guilhem** [comment]
As my work was a simple WIP, I let merge this as first version :)
We can iterate from this impressive base!

@PierreRambaud I add you as collaborator for this repo, never direct merge (except for obvious fix) and wait for 2 " :+1: " to merge a PR.
Welcome!

**Comment by PierreRambaud** [comment]
@guilhem Thanks a lot ;)

**Pull request merged**
